# Enable or disable inscription about 1.14 instruments
# Включает или выключает надпись о новых инструментах из 1.14
printNewInstrument: true
# bStats send
# Включить или выключить метрику(пожалуйста не вырубай, а то сидишь дома, печаль, печеньки кончились,
# и вот на метрику смотришь и понимаешь что твой плагин кому то нужен, и уже легче становится)
# Если вырубишь, то к тебе со спины придёт крипер, и взорвёт тебя вместе с алмазами, так что я бы на твоём месте подумал
bStats: true
economy:
  # Enable song sold by /musicbox shop
  # Включает продажу пластинок
  enable: true
  # Price for disc
  # Цена за диск в магазине
  price: 500
# Maximum sound distance in speaker mode
# Максимальная длина звука в режиме колонки
speakerRadius: 10
# Music bossbar setting
# Настройки музыкального боссбара
bossbar:
  # Enable or disable bossbar
  # Включает или выключает боссбар
  enable: true
  color: GREEN
  style: SEGMENTED_20

# Hologram settings above the player in column mode
# Настройки голограммы над игроком в режиме колонки
# Language setting
# Настройки языка, есть ru и en
lang: en
holo:
  # Enable or disable hologram(change requires server restart, not /musicbox reload)
  # Включает или выключает голограммы(для изменения нужно перезапустить сервер, а не просто перезагрузить плагин)
  enable: true
  # How high will the hologram be
  # Как высоко будет надпись над игроком
  height: 1.30
# Radius in which disc's will be heard from this plugin
# Как далеко будет слышно пластинки из этого плагина
jukeboxRadius: 64
# Enable or disable autodestroy range player if nobody hear him (Speaker mode, Sign,Jukeboxes) Time in seconds(0 disable)
# Включить или выключить автоуничтожение проигрывателей если никто их не слышит в течении N секунд
autoDestroy: 60